<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="vi"><head><title>Giỏ hàng</title></head><body><h1>Giỏ hàng của bạn</h1>
<c:choose><c:when test="${empty cart.items}"><div class="panel"><p>Giỏ hàng đang trống.</p><a class="button" href="${pageContext.request.contextPath}/products">Chọn sản phẩm</a></div></c:when><c:otherwise>
<p>Số lượng tối đa bằng tồn kho hiện tại. Giá và tồn kho được kiểm tra lại khi đặt hàng.</p>
<div class="panel table-wrap"><table><thead><tr><th>Sản phẩm</th><th>Đơn giá</th><th>Số lượng</th><th>Thành tiền</th><th></th></tr></thead><tbody>
<c:forEach items="${cart.items}" var="i"><tr><td><a href="${pageContext.request.contextPath}/product-detail?id=${i.productId}"><c:out value="${i.productName}"/></a><br><small>Tồn kho: ${i.stock}</small><c:if test="${i.productStatus ne 1 or i.stock lt i.quantity}"><p class="stock-warning">Ngừng bán hoặc không đủ tồn kho. Vui lòng sửa hoặc xóa.</p></c:if></td>
<td><fmt:formatNumber value="${i.unitPrice}" maxFractionDigits="0"/> ₫</td><td><form class="quantity-form" method="post" action="${pageContext.request.contextPath}/cart/update"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><input type="hidden" name="productId" value="${i.productId}"><input aria-label="Số lượng sản phẩm" type="number" name="quantity" min="1" max="${i.stock}" value="${i.quantity}" required><button class="outline">Cập nhật</button></form></td><td><fmt:formatNumber value="${i.subtotal}" maxFractionDigits="0"/> ₫</td><td><form method="post" action="${pageContext.request.contextPath}/cart/remove"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><input type="hidden" name="productId" value="${i.productId}"><button class="danger">Xóa</button></form></td></tr></c:forEach>
</tbody></table></div><div class="section-heading"><form method="post" action="${pageContext.request.contextPath}/cart/clear"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><button class="danger">Xóa toàn bộ giỏ hàng</button></form><div><p class="price">Tổng cộng: <fmt:formatNumber value="${cart.total}" maxFractionDigits="0"/> ₫</p><a class="button" href="${pageContext.request.contextPath}/checkout">Thanh toán COD</a></div></div>
</c:otherwise></c:choose><p><a href="${pageContext.request.contextPath}/products">← Tiếp tục mua sắm</a></p></body></html>
